[package]
name = "bitcoin"
version = "0.1.0"
authors = ["byron <zhion360@gmail.com>"]

[dependencies]
sha3 = "0.7.3"
blake2 = "0.7.1"
tiny-keccak = "1.4.2"
digest = { version = "0.7.2", features = ["std"]}
sodiumoxide = "0.1.0"
num-bigint = "0.2.0"
ramp = "0.5.0"
